version: '3.7'

services:

  api-slack-integration:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3100:3100"
    image: api-slack-integration
    container_name: api-slack-integration
    networks: 
      - api-network-driver

networks:
  api-network-driver:
     name: api-network-driver
