version: '3.7'

services:

  api-slack-integration:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3100:3100"
    image: api-slack-integration
    container_name: api-slack-integration
    network_mode: api-driver-network

networks:
  api-driver-network:
     name: api-driver-network
